### ISSUE TITLE
osx build cancelled?

### ISSUE THREAD

**Issue by smithsp** [conda-forge/fann2-feedstock#1]
@conda-forge/core 
On the code page of this repo, it indicates the osx build is cancelled
![image](https://user-images.githubusercontent.com/782050/33681530-b2916a0a-da79-11e7-9936-360791072aad.png)
Do I need to do something to enable that build, or have I done something in the recipe to accidentally cancel that build?  

(I am new to conda-forge.  Everything seems to be set up automatically, which is great, so maybe I just need to be more patient.  If this is not the right way to ask for help, please offer pointers to the place in the documentation I should have read.)

**Comment by isuruf** [comment]
It's still in a queue, see https://travis-ci.org/conda-forge/fann2-feedstock/builds
It'll take about half a day for the queue to be cleared up

**Comment by jakirkham** [comment]
You should have permissions to the Travis CI project for this repo. May require syncing your account on the Travis CI side if the repo is new. The cancellation is a product of Travis CI's more aggressive defaults for autocancellation (namely for branch builds), but can be fixed by simply restarting the build. We need to fix this on the `conda-smithy` side as noted in this [comment]( https://github.com/conda-forge/conda-smithy/issues/582#issuecomment-331569697 ).

**Comment by smithsp** [comment]
@isuruf @jakirkham 
Thanks.
I think this had more to do with my lack of experience with Travis, as I saw the cancelled badge, and didn't look into the branches tab of the Travis interface.  I suspect the cancelled badge showed up because the 1st build got cancelled when the "re-render after CI registration"  commit got pushed.
